### ISSUE TITLE
I can't download the dataset（S3 storage）.

### ISSUE THREAD

**Issue by jhunmk29** [norlab-ulaval/PercepTreeV1#1]

**Comment by VGrondin** [comment]
Hello, I tried it on Windows and linux with firefox navigator and both worked. Can you tell me what error message you are getting? 
Alternatively you can also try with this [OneDrive](https://ulavaldti-my.sharepoint.com/:f:/g/personal/vigro7_ulaval_ca/EvdPF5CryRVAhlBYoqk05ysBIMU46uN4cK4w2f3XtO9IOg?e=akD0Tt) link.

**Comment by jhunmk29** [comment]
this link is ok, thank u

**Comment by jhunmk29** [comment]
would you share your Unity model？

**Comment by VGrondin** [comment]
We would have like to, but we use some paid assets so we are unfortunately not authorized to freely distribute it.
