### ISSUE TITLE
Questions about penmanship and undefined variables in projects

### ISSUE THREAD

**Issue by CharmingZh** [norlab-ulaval/PercepTreeV1#4]
Dear Author.

I was researching your project and found a small error. Specifically, I see a typo in the file `train_synth_RGB.py` and I would like to submit a pull request to fix it. I would appreciate it if you would accept my changes.

https://github.com/norlab-ulaval/PercepTreeV1/blob/faca032256c348357ecfb23ac8eebceb97389677/train_synth_RGB.py#L353
---
Also, I have a question about an undefined variable. In the file `train_synth_RGB.py`, there is a variable that doesn't seem to be defined. I tried to find the documentation and source code, but I couldn't find any information about it. How should I use this variable? Or am I missing some key information?

https://github.com/norlab-ulaval/PercepTreeV1/blob/faca032256c348357ecfb23ac8eebceb97389677/train_synth_RGB.py#L334

Thank you for your time and patience, and I look forward to hearing from you.

**Comment by pomerlef** [comment]
Thanks for reporting @CharmingZh. @VGrondin will have a look in the coming days.

**Comment by VGrondin** [comment]
Hi @CharmingZh, thanks for fixing the mistake with the pull request. As for the indefinded `opts` variable, I once used it to define the model configuration, but it is dead code now so you can comment it no problem.
