### ISSUE TITLE
Availability of the depth images

### ISSUE THREAD

**Issue by hoeoek** [norlab-ulaval/PercepTreeV1#9]
First, great job with this dataset! 

When can we expect the depth images from SynthTree43k to be published?

**Comment by VGrondin** [comment]
Hi @hoeoek, I will try to upload it this weekend, will let you know when it's available.

**Comment by BaderTim** [comment]
Hey @VGrondin , I am also interested in the depth images. In the README, it still says 'SOON' 😢

**Comment by VGrondin** [comment]
Hey guys link is (finally) up!

**Comment by BaderTim** [comment]
Thanks! :)

**Comment by akapildevkumar** [comment]
Thanks for adding the depth images. Is it possible to add training and inferencing script for depth images?
